services:
  erudit-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erudit-admin
    image: erudit-admin
    ports:
      - '127.0.0.1:3001:3000'
    env_file:
      - .env.production
    networks:
      - erudit-admin-network
    restart: unless-stopped

networks:
  erudit-admin-network:
    name: erudit-admin-network
    driver: bridge
